version: '3.9'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./app/database.db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3005:3000"
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
