"""First migration

Revision ID: 5f3d731cb6de
Revises: 
Create Date: 2024-12-10 16:40:09.417455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f3d731cb6de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('title', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('tags', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_notes_title'), 'notes', ['title'], unique=False)
    op.add_column('tasks', sa.Column('description', sa.String(length=1000), nullable=False))
    op.add_column('tasks', sa.Column('priority', sa.Enum('High', 'Medium', 'Low', name='priorityenum'), nullable=False))
    op.add_column('tasks', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tasks', 'due_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_tasks_title', table_name='tasks')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_tasks_title', 'tasks', ['title'], unique=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'due_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('tasks', 'is_completed')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'description')
    op.drop_index(op.f('ix_notes_title'), table_name='notes')
    op.drop_column('notes', 'tags')
    op.drop_column('notes', 'title')
    # ### end Alembic commands ###
